### ISSUE TITLE
Error and kick player on join

### ISSUE THREAD

**Issue by kirr9999** [OpenMods/OpenModsLib#42]
I use OpenBlocks and OpenModsLib on a cauldron server and forge client 1.7.10. And I was kicked from a server on join and this error is printed to the console:
```
[19:24:22] [Client thread/ERROR]: There was a critical exception handling a packet on channel OpenMods|M
java.io.EOFException
        at java.io.DataInputStream.readInt(Unknown Source) ~[?:1.7.0_71]
        at openmods.sync.SyncableInt.readFromStream(SyncableInt.java:21) ~[SyncableInt.class:?]
        at openmods.sync.SyncMap.readFromStream(SyncMap.java:153) ~[SyncMap.class:?]
        at openmods.sync.InboundSyncHandler.channelRead0(InboundSyncHandler.java:26) ~[InboundSyncHandler.class:?]
        at openmods.sync.InboundSyncHandler.channelRead0(InboundSyncHandler.java:15) ~[InboundSyncHandler.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650) [bao.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) [bao.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
        at r.iIiIIiiIIiI.<init>(ui:15) [launcher.jar:?]
        at r.iIiIIiiIIiI.main(ui:103) [launcher.jar:?]
[19:24:22] [Netty Client IO #3/INFO]: openmods.network.IdSyncManager.onDisconnect(IdSyncManager.java:124): Disconnected, restoring local data
```
________________________________________________________________
Please fix it.

**Comment by boq** [comment]
Looks like version mismatch. Please make sure you have exact same OpenModsLib and OpenBlocks FILES on both sides (value reported in-game is not enough). If they are the same, then report it here.

**Comment by kirr9999** [comment]
I'm sorry, the server used an older version than the client.
