### ISSUE TITLE
[1.10.2] Milking cow crash

### ISSUE THREAD

**Issue by gtokarz** [OpenMods/OpenModsLib#64]
When you try to milk cow with bucket from far distance, error appears. There is no error when you are close to cow.

```
java.lang.NullPointerException: Unexpected error
	at openmods.liquids.BucketFillHandler.onBucketFill(BucketFillHandler.java:62)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_615_BucketFillHandler_onBucketFill_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:366)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:40)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:495)
	at PlayerControllerOF.func_187101_a(PlayerControllerOF.java:73)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1544)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by boq** [comment]
Thank you for the report, but 1.10.2 port is pre-alpha and we are not collection bugs for that version yet.
