### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by joaco1808-jpg** [OpenMods/OpenModsLib#89]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2 (1).jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  McLib core mod (mclib-2.3.5-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.65_mc1.12.2 (1).jar)
  HCASM (HammerLib-1.12.2-2.0.6.28.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31 (1).jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 2/26/22 6:01 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from TLSkinCape (tlauncher_custom_cape_skin)
Caused by: java.lang.NoClassDefFoundError: net.minecraft.client.Minecraft
	at org.tlauncher.skin.cape.util.PreparedProfileManager.<init>(PreparedProfileManager.java:43)
	at org.tlauncher.skin.cape.TLSkinCape.event(TLSkinCape.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:729)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:112)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:342)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:269)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:688)
	at java.lang.Thread.run(Thread.java:827)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:223)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:954)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:899)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:882)
	... 37 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@9e133f63 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:311)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:183)
	... 40 more
Caused by: java.lang.RuntimeException: Attempted to load class bib for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 42 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Magma Version: 88f081a-DEV
	Operating System: Linux (amd64) version 3.10.0-1160.25.1.el7.x86_64
	Java Version: 1.8.0_322, International Business Machines Corporation
	Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220128_306 (JIT enabled, AOT enabled)
OpenJ9   - 9dccbe076
OMR      - dac962a28
JCL      - c1d9a7af7c based on jdk8u322-b06), Eclipse OpenJ9
	Memory: 337318208 bytes (321 MB) / 739508224 bytes (705 MB) up to 17179869184 bytes (16384 MB)
	JVM Flags: 8 total; -Xoptionsfile=/opt/java/openjdk/jre/lib/amd64/default/options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle -Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,readonly,nonFatal -Xms128M -Xmx16384M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 58 mods loaded, 57 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version                  | Source                                        | Signature                                |
	|:----- |:-------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft                  | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHIJ | mcp                        | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHIJ | FML                        | 8.0.99.99                | server.jar                                    | None                                     |
	| LCHIJ | forge                      | 14.23.5.2860             | server.jar                                    | None                                     |
	| LCHIJ | creativecoredummy          | 1.0.0                    | minecraft.jar                                 | None                                     |
	| LCHIJ | openmodscore               | 0.12.2                   | minecraft.jar                                 | None                                     |
	| LCHIJ | itemblacklist              | 1.4.3                    | ItemBlacklist-1.4.3.jar                       | None                                     |
	| LCHIJ | damageindicatorsmod        | 1.0                      | 1.12.2DamageIndicatorsMod-3.5.1.jar           | None                                     |
	| LCHIJ | securitycraft              | v1.8.23.2                | [1.12.2]+SecurityCraft+v1.8.23.2.jar          | None                                     |
	| LCHIJ | mantle                     | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJ | jei                        | 4.15.0.289               | jei_1.12.2-4.15.0.289.jar                     | None                                     |
	| LCHIJ | chisel                     | MC1.12.2-1.0.1.44        | Chisel-MC1.12.2-1.0.1.44.jar                  | None                                     |
	| LCHIJ | tconstruct                 | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LCHIJ | thedragonlib               | 1.12.2-5.3.0             | thedragonlib-1.12.2-5.3.0 (1).jar             | None                                     |
	| LCHIJ | armorplus                  | 1.12.2-11.28.0.69        | armorplus-1.12.2-11.28.0.69.jar               | None                                     |
	| LCHIJ | baubles                    | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJ | biomesoplenty              | 7.0.1.2444               | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar | None                                     |
	| LCHIJ | bookworm                   | 1.12.2-2.5.2.1           | bookworm-1.12.2-2.5.2.1.jar                   | None                                     |
	| LCHIJ | chiselsandbits             | 14.33                    | chiselsandbits-14.33.jar                      | None                                     |
	| LCHIJ | chunkpregenerator          | 2.5.0                    | ChunkPregenerator-V1.12-2.5.0.jar             | None                                     |
	| LCHIJ | mca                        | 6.1.0                    | Comes-Alive-espanol.jar                       | None                                     |
	| LCHIJ | conarm                     | 1.2.5.10                 | conarm-1.12.2-1.2.5.10.jar                    | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCHIJ | creativecore               | 1.10.0                   | CreativeCore_v1.10.65_mc1.12.2 (1).jar        | None                                     |
	| LCHIJ | customnpcs                 | 1.12                     | CustomNPCs_1.12.2-(05Jul20).jar               | None                                     |
	| LCHIJ | dawnoftimebuilder          | 1.0.7                    | dawnoftime_builder_edition-1.0.7.jar          | None                                     |
	| LCHIJ | ebwizardry                 | 4.3.4                    | ElectroblobsWizardry-4.3.4-MC1.12.2.jar       | None                                     |
	| LCHIJ | extrautils2                | 1.0                      | extrautils2-1.12-1.9.9 .jar                   | None                                     |
	| LCHIJ | llibrary                   | 1.7.20                   | llibrary-1.7.20-1.12.2 (2).jar                | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJ | fossil                     | 8.0.5                    | fossilsarcheology-8.0.5 (1).jar               | None                                     |
	| LCHIJ | cfm                        | 6.3.1                    | furniture-6.3.1-1.12.2.jar                    | None                                     |
	| LCHIJ | hammercore                 | 2.0.6.28                 | HammerLib-1.12.2-2.0.6.28.jar                 | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJ | waila                      | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCHIJ | ido                        | 1.0.6                    | ido-1.12.2-1.1.0.jar                          | None                                     |
	| LCHIJ | improvableskills           | 12.4.67                  | ImprovableSkills-1.12.2-12.4.67.jar           | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJ | infernalmobs               | 1.7.6                    | InfernalMobs-1.12.2.jar                       | None                                     |
	| LCHIJ | ironchest                  | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.71.846.jar               | None                                     |
	| LCHIJ | ironfurnaces               | 1.3.5                    | ironfurnaces-1.3.5.jar                        | None                                     |
	| LCHIJ | jjcoin                     | 1.0.5                    | JJ+Coin+1.12-1.12.2-v1.0.5.jar                | None                                     |
	| LCHIJ | journeymap                 | 1.12.2-5.7.0             | journeymap-1.12.2-5.7.0.jar                   | None                                     |
	| LCHIJ | malisiscore                | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                  | None                                     |
	| LCHIJ | malisisdoors               | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| LCHIJ | mclib                      | 2.3.5                    | mclib-2.3.5-1.12.2.jar                        | None                                     |
	| LCHIJ | modularvc                  | 1.1.1                    | ModularVoiceChat-1.1.1.jar                    | None                                     |
	| LCHIJ | mowziesmobs                | 1.5.8                    | mowziesmobs-1.5.8.jar                         | None                                     |
	| LCHIJ | mutantbeasts               | 1.12.2-1.0.2             | MutantBeasts-1.12.2-1.0.2.jar                 | None                                     |
	| LCHIJ | openmods                   | 0.12.2                   | OpenModsLib-1.12.2-0.12.2 (1).jar             | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJ | openblocks                 | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJ | ordinarycoins              | 1.5                      | ordinarycoins-1.12.2-1.5.jar                  | None                                     |
	| LCHIJ | playerrevive               | 1.0                      | PlayerRevive_v1.2.40_mc1.12.2.jar             | None                                     |
	| LCHIJ | rustic                     | 1.1.7                    | rustic-1.1.7 .jar                             | None                                     |
	| LCHIJ | tinkertoolleveling         | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar           | None                                     |
	| LCHIE | tlauncher_custom_cape_skin | 1.4                      | tlskincape_1.12.2-1.4.jar                     | None                                     |
	| LCHI  | tombstone                  | 4.4.7                    | tombstone-1.12.2-4.4.7.jar                    | None                                     |
	| LCHI  | torchmaster                | 1.8.0.79                 | torchmaster_1.12.2-1.8.0.79.jar               | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| LCHI  | travelersbackpack          | 1.0.35                   | TravelersBackpack-1.12.2-1.0.35.jar           | None                                     |
	| LCHI  | walljump                   | 1.3.2                    | walljump-1.12.2-1.3.2.jar                     | None                                     |
	| LCHI  | xlfoodmod                  | 1.12.2-1.9.2             | XL-Food-Mod-1.12.2-1.9.2.jar                  | None                                     |
	| UD    | mclib_core                 | 2.3.5                    | minecraft.jar                                 | None                                     |

	Loaded coremods (and transformers): 
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2 (1).jar)
  openmods.core.OpenModsClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
McLib core mod (mclib-2.3.5-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
CreativePatchingLoader (CreativeCore_v1.10.65_mc1.12.2 (1).jar)
  
HCASM (HammerLib-1.12.2-2.0.6.28.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31 (1).jar)
  team.chisel.ctm.client.asm.CTMTransformer
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	HammerCore Debug Information: 
		Dependent Mods:
			-Improvable Skills (improvableskills) @ 12.4.67

	Profiler Position: N/A (disabled)
	Player Count: 0 / 30; []
	Is Modded: Definitely; Server brand changed to 'Magma'
	Type: Dedicated Server (map_server.txt)
```

**Comment by boq** [comment]
`TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)` issue
